[package]
name = "colorful-triples"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
bitintr = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.115"

[profile.release]
debug = true
