name:                colorful-pythagorean-triples
version:             0.1.0.0
github:              "jorpic/colorful-pythagorean-triples"
license:             MIT
author:              "Max Taldykin"
maintainer:          "jorpic@gmail.com"
copyright:           "Max Taldykin"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/jorpic/colorful-pythagorean-triples#readme>


default-extensions:
- FlexibleContexts
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- NoMonomorphismRestriction
- OverloadedStrings
- RecordWildCards
- TupleSections

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  py3:
    main:                Main.hs
    source-dirs:         hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - containers
    - diagrams-lib
    - diagrams-graphviz
    - diagrams-svg
    - graphviz
    - process
